//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubscriberWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientStockTrackerEntities : DbContext
    {
        public ClientStockTrackerEntities()
            : base("name=ClientStockTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PriceHistory> PriceHistories { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
    }
}
