//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SubscriberWebAPI.Models
{
    public partial class Subscription
    {
        public int id { get; set; }
        [Required]
        public string user_id { get; set; }
        [Required]
        public int stock_id { get; set; }

        public Subscription(int stock_id, string user_id)
        {
            this.user_id = user_id;
            this.stock_id = stock_id;
        }
    }
}
